### ISSUE TITLE
Feature request: `fleekStorage.upload` returns `httpUploadProgress` progress events 

### ISSUE THREAD

**Issue by sharad-s** [FleekHQ/fleek-storage-js#14]
Very helpful for larger files. Using Fleek to store larger media files, however UX takes a hit when uploading a file that's around 30+MB.  I would like to listen to `httpUploadProgress` events so that I could show a progress bar client side for visual feedback on the upload status.

**Comment by SamueleA** [comment]
That's a really good idea! I'll consider implementing it when some I can free up some time

**Comment by rlogiacco** [comment]
I would love to see this implemented: any way I can speed things up?

**Comment by SamueleA** [comment]
version 1.0.19 now exposes the httpUploadProgress event.
You can pass a callback function like so:

```
    const uploadedFile = await fleekStorage.upload({
      ...input,
      data: fileData,
      httpUploadProgressCallback: (event) => {
        console.log(Math.round(event.loaded/event.total*100)+ '% done');
      }
    });
```

**Comment by SamueleA** [comment]
Closing the issue since the feature is in

**Comment by rlogiacco** [comment]
LOVELY!
